version: '3.8'
services:
  site-uasz:
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./css:/usr/share/nginx/html/css
      - ./js:/usr/share/nginx/html/js
    restart: unless-stopped
